### ISSUE TITLE
1.9.1/1.9.2: diff_to_html.rb:320:in `check_handled_commits': undefined method `to_a' for "....

### ISSUE THREAD

**Issue by mfn** [git-commit-notifier/git-commit-notifier#39]
With current master I get this on 1.9.1 and 1.9.2 :
    /data/git/git-commit-notifier/lib/diff_to_html.rb:320:in `check_handled_commits': undefined method`to_a' for "b77509dca97b0fddf9b682656b7ac8817d4b2a5d":String (NoMethodError)
        from /data/git/git-commit-notifier/lib/diff_to_html.rb:351:in `diff_between_revisions'
        from /data/git/git-commit-notifier/lib/commit_hook.rb:63:in`run'
        from /data/git/git-commit-notifier/bin/git-commit-notifier:21:in `<main>'
1.8.6 didn't work either, I get
    /data/git/git-commit-notifier/bin/../lib/diff_to_html.rb:348:in`diff_between_revisions': wrong argument type Symbol (expected Proc) (TypeError)
        from /data/git/git-commit-notifier/bin/../lib/commit_hook.rb:63:in `run'
        from /data/git/git-commit-notifier/bin/git-commit-notifier:21
there, but I just figured it's too old anyway.

I got it working with 1.8.7 only.
